### PR TITLE
Btrfs

### LINKED ISSUE #44: add btrfs

### PR DESCRIPTION
**Pull request by zivillian**
Fixes #44 

The implementation is read-only and may not be feature complete. I've tested this against various btrfs filesystems created under Ubuntu 14.04 & 16.04. There is still much room for performance optimization - especially the lookup using all the other available trees. Please consider this an early beta.

The implementation is mainly based on the [documentation](https://btrfs.wiki.kernel.org/index.php/Main_Page#Developer_documentation).

I've added a depency to [lzo.net](https://www.nuget.org/packages/lzo.net) (which I created as part of this project #42 ), but I guess this may also be usable to someone else.

### CODE REVIEW

**Comment by LordMike** [comment]
Damn. :)

👍

**Comment by zivillian** [comment]
I just saw, that the build genrates a warning about lzo.net not beeing signed, so I guess we should first decide how to deal with #58 before merging this.

**Comment by zivillian** [comment]
And now I saw, that you fixed this by removing PublicSign. In #37 I suggested using `<PublicSign Condition="'$(OS)' != 'Windows_NT'">` which I found in some tutorials, but I've no Idea what the reason behind this may be.

Should I add a strong name version of lzo.net?

**Comment by LordMike** [comment]
Yes. The reasoning so far has been:

* A Strong Name Signed assembly may only load Strong Name Signed dependencies
* Any other assembly may load both SNS dependencies and non-signed dependencies

So by signing, you allow others who also sign to use yours, while not restricting those who do not sign.

Signing does mean, however, that it's not possible to substitute one built version for another (since the public key is part of the assembly name). Some projects require that their dependencies are not signed, in order for them to (amongst other reasons) quickly be able to replace one assembly for one they compile themselves.

**Comment by zivillian** [comment]
I've added strong name singing to lzo.net and updated the reference from DiscUtils.Btrfs.

**Comment by LordMike** [comment]
Well. Here goes .. :)

**Pull request merged**
