### PR TITLE
Nfs: Add read/write support for most objects, unit tests

### PR DESCRIPTION
**Pull request by qmfrederik**
The current NFS implementation acts a a client of a NFS server. There's write support for messages which are sent to a NFS server and read support for messages which are received from a NFS server.

This PR adds read/write support for all these messages, which will allow you to build a NFS server using DiscUtils.

Also adds unit tests for roundtripping objects (e.g. serializing & deserializing them).

### CODE REVIEW

**Comment by LordMike** [comment]
Are you in need of an NFS server? :)

**Comment by qmfrederik** [comment]
Yes ;-)

**Comment by LordMike** [comment]
Well. I have next to no knowledge on NFS, so this ones on you :)

**Comment by qmfrederik** [comment]
Thanks 😄 

I'm going to squash & merge this one, I think the changes are very low risk (adding new functionality + covered by unit tests).

**Pull request merged**
