### PR TITLE
Add support for LZFSE-encoded runs

### PR DESCRIPTION
**Pull request by qmfrederik**
DMG images can contain run types which are compressed using the LZFSE run type (0x80000007). See https://github.com/darlinghq/darling-dmg/commit/c765e9740ccb708afe170871add9e9bf52115274 for some more information.

This PR adds support for that. It is contingent on a LZFSE-decoder, which I did not port to .NET. Rather, the code will P/Invoke https://github.com/lzfse/lzfse/, which is available as a VCPKG module, via Homebrew and on Linux.

Adding managd LZFSE support may be a nice follow-up, but I was hoping we can merge this to unblock some scenarios I have (and P/Invoking is fine for those scenarios).

### CODE REVIEW

**Comment by qmfrederik** [comment]
Ping @LordMike

**Comment by LordMike** [comment]
Right.

Don't we need a dependency for the LZFSE projects packages to ensure the native binaries are present?

**Comment by qmfrederik** [comment]
It's a tricky scenario. There's no easy way to formally declare a dependency on a native library from a managed library.

You can try to package the native assets in the NuGet package. This works well for Windows and macOS because those OSes have a stable ABI. This doesn't work for Linux because you're likely to end up compiling special libraries for each Linux distro and version.

I can try to package native assets for Windows & macOS for lzfse and put it up on NuGet.

**Comment by qmfrederik** [comment]
Allright, here you go. I packaged a .NET wrapper for LZFSE and the native libraries for LZFSE for Windows & macOS as [lzfse-net](https://github.com/quamotion/lzfse-net) and took a dependency on that.

**Comment by LordMike** [comment]
Ok, so I looked at the code more closely, and it's probably fine - but:

* You're changing builds, adding nuget pushing - are you perhaps targeting the wrong branch, or whats up?
* Can we perhaps make the LZFSE implementation a setting, much like registering the libraries for use. If we encounter LZFSE runs and it's disabled, we throw and report a helpful message - else we just try using the library (without the dependency)?

**Comment by qmfrederik** [comment]
I'm going to go ahead and merge this PR. You'll get a `DllNotFoundException` should the P/invoke to lzfse fail.

**Pull request merged**
