### PR TITLE
XFS v5

### PR DESCRIPTION
**Pull request by zivillian**
This PR updates Data Fork offset for Inode Version 3 and also fixes the invalid interpretation of ForkOffset

### CODE REVIEW

**Comment by zivillian** [comment]
I've added some more commits to support reading XFSv5. I've also added another test image with an XFSv5 filesystem and copied the corresponding unit test.

**Comment by LordMike** [comment]
@zivillian this is all good then?

**Comment by zivillian** [comment]
@LordMike as far as I can tell, this shoud be fine. The unit tests are working, I've added some check for the incompatible flags in the superblock, and I was able to read the supplied vhd.
Maybe @travist13 has some additional feedback.

**Comment by travist13** [comment]
@zivillian I didn't see any issues with the code. The incompatible features may be a problem for us but I will have to test it on our images to find out. Thanks!

**Pull request merged**
