### PR TITLE
create DiscUtils.Streams

### LINKED ISSUE #19: Add DiscUtils.Streams package
DiscUtils contains a lot of internal classes which allow you to consume streams - for example, there's a `SubStream` class or a `ConcatStream` class.

I need such streams from time to time in other projects, and one of the limitations has always been that those classes are marked `internal`.

Hence the suggestion is to:
- Move those classes to a `DiscUtils.Stream` project
- Make them public

@LordMike Thoughts?

### PR DESCRIPTION
**Pull request by zivillian**
fixes #19

### CODE REVIEW

**Comment by LordMike** [comment]
@zivillian I could commit to your branch once, as I fixed stuff in the Github web UI.. But I can't commit from my client .. odd..

Can you give me write/push access to your fork of DiscUtils?

**Comment by zivillian** [comment]
I've added you as a "Collaborator", let me know if this works

**Comment by LordMike** [comment]
I'm still unable to push. But you're welcome to fix my mistakes - they're quite quick.

These are the files that just need a quick touchup:
image

**Comment by LordMike** [comment]
Note that the project we're talking about is this: https://github.com/ahdde/DiscUtils.
Githubs Web UI also says I don't have write access to the repo.

**Comment by LordMike** [comment]
Never mind... I got a mail about an invite to the repo.. :/

**Comment by LordMike** [comment]
I never figured out pushing to your repo.. Maybe Github is experiencing som backlash from their short breakdown earlier today.. It's been merged and fixed.

**Comment by qmfrederik** [comment]
@zivillian @LordMike Cool, thanks!

**Pull request merged**
